language: python
python:
  - "3.5"
  - "3.6"

env:
  global:
    - PGPORT=55432

addons:
  postgresql: 10
  apt:
    packages:
      - postgresql-client-10

services:
  - postgresql

install:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE ROLE wiki SUPERUSER LOGIN PASSWORD 'wiki';" -U postgres
  - psql -c 'CREATE DATABASE wiki_analysis;' -U postgres
