language: python
dist: trusty
python:
  - "3.6"
addons:
  postgresql: "9.5"
services:
  - postgresql
install:
  - pip install -r requirements.txt
  - pip install coverage
  - pip install codecov
before_script:
  - psql -c "CREATE DATABASE wiki_analysis;" -U postgres
  - psql -c "CREATE ROLE wiki SUPERUSER LOGIN PASSWORD 'wiki';" -U postgres
script:
  - coverage run wiki_analysis.py din -d
after_success:
  - codecov
